version: "2.0"

services:
  php-app:
    image: php:7.2-apache
    ports:
      - 8123:80
    volumes:
      - ./www:/var/www/html

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
